# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Desconocido', max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, default='Desconocido', max_length=2000, null=True)),
                ('alimentacion', models.TextField(blank=True, default='Desconocida', max_length=2000, null=True)),
                ('habitat', models.TextField(blank=True, default='Desconocida', max_length=2000, null=True)),
                ('localizacion', models.TextField(blank=True, default='Desconocida', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Fotos_de_Aves')),
                ('latitud', models.DecimalField(decimal_places=6, default='0', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, default='0', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnacimiento', models.DateField(null=True)),
                ('estudios', models.CharField(default='Desconocidos', max_length=500)),
                ('fotoPerfil', models.ImageField(upload_to='Fotos_de_Perfil')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ave',
            name='fotos',
            field=models.ManyToManyField(to='VayaPajaro.Foto'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VayaPajaro.Ave'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VayaPajaro.Usuario'),
        ),
    ]
