# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VayaPajaro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='longitud',
        ),
    ]
