# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VayaPajaro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
    ]
