# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VayaPajaro', '0002_auto_20181012_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(upload_to='Fotos_de_Aves'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(upload_to='Fotos_de_Perfil'),
        ),
    ]
