# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VayaPajaro', '0004_auto_20181016_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='Desconocido', max_length=60),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombreCuenta',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
    ]
