# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VayaPajaro', '0006_auto_20181016_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fnacimiento',
            field=models.DateField(null=True),
        ),
    ]
